/**********************************************************************
*
*   Component generated by Quest
*
*   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts. 
*   To preseve that abilty, always export from Quest to regenerate this file.
*   To setup props, bindings and actions, use the Quest editor
*   Code Logic goes in the hook associated with this component
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

import { styled } from '@mui/material/styles';
import Dashboard from './Dashboard';

 
const Dashboard2 = styled("div")({  
  display: `flex`,  
  position: `relative`,  
  isolation: `isolate`,  
  flexDirection: `column`,  
  justifyContent: `flex-start`,  
  alignItems: `flex-start`,  
  padding: `0px`,  
  boxSizing: `border-box`,  
});
  
const Dashboard3 = styled(Dashboard)(({ theme }) =>({  
  alignSelf: `stretch`,  
  margin: `0px`,  
}));
 
function Dashboard1(props) {
  return (
    <Dashboard2 className={props.className} >
      <Dashboard3   />
    </Dashboard2>
  );
}

export default Dashboard1;
