/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useProductCard1 = () => {
  let data: any = {price:"$3333.333"};
  const handleClick = (): any => {};

  let fns: any = {handleClick};
  return {data, fns};
}

export default useProductCard1;